### PR TITLE
fixed broken links of testgrid dashboard

### PR DESCRIPTION
**Pull request by siddhikhapare**
What type of PR is this?
/kind documentation

Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/test-infra/issues/30370

### CODE REVIEW

**Review by pohly — APPROVED** [review]
/ok-to-test
/lgtm
/approve

**Comment by AdityaVardhanSingh** [comment]
Hey, can you help me with how #30370 closed as there are other broken links remaining to be fixed?

**Comment by siddhikhapare** [comment]
@pohly Thank you for your guidance.

**Pull request merged**
