### PR TITLE
Update go version to 1.21 to match k/k

### PR DESCRIPTION
**Pull request by dannawang0221**
Refer to https://github.com/kubernetes/kubernetes/blob/master/.go-version

```release-note
Update go version to 1.21
```

### CODE REVIEW

**Comment by sunnylovestiramisu** [comment]
New csi-test release version created: https://github.com/kubernetes-csi/csi-test/releases/tag/v5.2.0

**Comment by sunnylovestiramisu** [comment]
Can you change this line to https://github.com/kubernetes-csi/csi-release-tools/blob/master/prow.sh#L243 [v5.2.0](https://github.com/kubernetes-csi/csi-test/releases/tag/v5.2.0)?

**Comment by pohly** [comment]
Workaround is in https://github.com/kubernetes-csi/csi-release-tools/pull/243

**Pull request merged**
