### PR TITLE
Adding s390x travis support

### PR DESCRIPTION
**Pull request by srajmane**
- Added s390x support for travis
- Disable shellcheck for s390x
- Added docker image name with arch name.

### CODE REVIEW

**Comment by srajmane** [comment]
@pohly @msau42 Could you please have a look ?

**Comment by msau42** [comment]
/assign @pohly 
I believe we want to move away from travis and start migrating our release infra to the system supported by wg-k8s-infra.

**Comment by pohly** [comment]
Let's focus on the approach outlined in https://github.com/kubernetes-csi/node-driver-registrar/pull/63 instead. That also is open at this time, but it looks more promising than extending the build rules for every single additional architecture and continuing to rely on TravisCI.

**Comment by srajmane** [comment]
Closing in favor of Prow builds.

**Pull request closed without merging**
