### PR TITLE
chore: update CSI driver version to 1.15

### PR DESCRIPTION
**Pull request by TerryHowe**
Updating release tools similar to:

https://github.com/kubernetes-csi/csi-test/pull/431

for:
https://github.com/kubernetes-csi/csi-test/pull/560

### CODE REVIEW

**Comment by jsafrane** [comment]
/retest
> remote: fatal: could not fetch b18c53581356c52a220a2baf1c8cf3fd9c57dda6 from promisor remote        
error: git upload-pack: git-pack-objects died with error.

is it a git hiccup or is is permanent?

**Comment by TerryHowe** [comment]
https://github.com/kubernetes-csi/csi-test/pull/561/files should fix the broke build

**Comment by jsafrane** [comment]
Thanks a lot for your PRs!

**Pull request merged**
