### PR TITLE
Validate OWNERS files - remove sections about emeritus reviewers

### PR DESCRIPTION
**Pull request by peizhouyu**
please see [kubernetes/community#6334](https://github.com/kubernetes/community/issues/6334)

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

What type of PR is this?   

/kind cleanup

What this PR does / why we need it:

Which issue(s) this PR fixes: 

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?  
```
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```

```

### CODE REVIEW

**Comment by peizhouyu** [comment]
/assign @humblec 
Thanks

**Comment by Garima-Negi** [comment]
Hi, this seems like a duplicate of [https://github.com/kubernetes-csi/csi-release-tools/pull/185](https://github.com/kubernetes-csi/csi-release-tools/pull/185) which is now merged

**Pull request closed without merging**
