### PR TITLE
Master to main cleanup

### PR DESCRIPTION
**Pull request by anubha-v-ardhan**
Needed by https://github.com/kubernetes/k8s.io/issues/1597

/kind cleanup

### CODE REVIEW

**Comment by pohly** [comment]
/ok-to-test
/lgtm
/approve

@anubha-v-ardhan we have a process for copying this repo into the other repos. Please close all of your other PRs because they cannot be merged as-is. I can kick off a mass update once this PR is merged.

**Comment by anubha-v-ardhan** [comment]
Thanks @pohly, I didn't know that was possible. I have deleted all my other PRs

**Pull request merged**
