### PR TITLE
use new GOTOOLCHAIN env to manage go version

### PR DESCRIPTION
**Pull request by huww98**
Should prevent go from automatically downloading newer toolchains. And ensure the specified version is used.

BTW, this also enables support for platforms other than linux/amd64

```release-note
Requires at least go1.21 to run prow.sh
```

See also:
- https://go.dev/doc/toolchain
- https://github.com/kubernetes/kubernetes/pull/120279

It works like this:

```
$ go version
go version go1.23.1 darwin/arm64

$ run_with_go "" go version
2024年11月 9日 星期六 00时59分35秒 CST go1.23.1 /Users/huww98/Downloads$ go version
go version go1.23.1 darwin/arm64

$ run_with_go "1.23.0" go version
2024年11月 9日 星期六 00时59分51秒 CST go1.23.0 /Users/huww98/Downloads$ go version
go version go1.23.0 darwin/arm64

$ run_with_go "1.23.2" go version
go: downloading go1.23.2 (darwin/arm64)
2024年11月 9日 星期六 01时01分21秒 CST go1.23.2 /Users/huww98/Downloads$ go version
go version go1.23.2 darwin/arm64

$ export PATH=~/Downloads/go1.18.10/bin:$PATH
$ go version
go version go1.18.10 darwin/arm64
$ run_with_go "1.23.0" go version
ERROR: Please install Go 1.21+
exit
```
```
# remove go from PATH
$ run_with_go "1.21.0" go version
bash: go: command not found
ERROR: Please install Go 1.21+
exit
```

### CODE REVIEW

**Review by pohly — COMMENTED** [review]
The change itself is fine.

I'm just wondering whether a bigger revamp of how Go versions are picked might be possible. For example, `CSI_PROW_GO_VERSION_E2E` could be removed in favor of simply not overriding the Go version at all when building inside the k/k repo. Go should be able to figure out if it needs a newer Go version based on the `go.mod` there. If the current Go version is newer, then there should be no need to download an older version.

**Comment by huww98** [comment]
> If the current Go version is newer, then there should be no need to download an older version.
Downloading an older version should help with reproducible build/test result.

**Comment by Rakshith-R** [comment]
hey @huww98 ,

I think this pr is responsible for all the k8s-1.29 pull job failures on all sidecar repos.

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-csi_external-snapshot-metadata/83/pull-kubernetes-csi-external-snapshot-metadata-1-29-on-kubernetes-1-29/1866439937163792384
```

HEAD is now at 3f7a50f3 Release commit for Kubernetes v1.29.0
Tue Dec 10 11:29:33 UTC 2024 go1.23.3 /home/prow/go/src/k8s.io/kubernetes$ git clean -fdx
Tue Dec 10 11:29:33 UTC 2024 go1.21.5 $ make WHAT=test/e2e/e2e.test -C/home/prow/go/src/k8s.io/kubernetes
make: Entering directory '/home/prow/go/src/k8s.io/kubernetes'
+++ [1210 11:29:34] Building go targets for linux/amd64
    k8s.io/kubernetes/test/e2e/e2e.test (test)
make: Leaving directory '/home/prow/go/src/k8s.io/kubernetes'
Tue Dec 10 11:36:06 UTC 2024 go1.21.5 $ make WHAT=vendor/github.com/onsi/ginkgo/ginkgo -C/home/prow/go/src/k8s.io/kubernetes
make: Entering directory '/home/prow/go/src/k8s.io/kubernetes'
+++ [1210 11:36:06] Building go targets for linux/amd64
    github.com/onsi/ginkgo/v2/ginkgo (non-static)
go: downloading go1.21.5 (linux/amd64)
go: download go1.21.5 for linux/amd64: toolchain not available
!!! [1210 11:36:06] Call tree:
!!! [1210 11:36:06]  1: /home/prow/go/src/k8s.io/kubernetes/hack/lib/golang.sh:799 kube::golang::build_some_binaries(...)
!!! [1210 11:36:06]  2: /home/prow/go/src/k8s.io/kubernetes/hack/lib/golang.sh:958 kube::golang::build_binaries_for_platform(...)
!!! [1210 11:36:06]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [1210 11:36:06] Call tree:
!!! [1210 11:36:06]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [1210 11:36:06] Call tree:
!!! [1210 11:36:06]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
```

@avorima ^

cc @jsafrane @pohly

**Comment by Rakshith-R** [comment]
Probably because the complete 1.21.z version is not defined in https://github.com/kubernetes/kubernetes/blob/release-1.29/go.mod#L9

**Comment by avorima** [comment]
@Rakshith-R could we update the used k/k version to 1.30 or 1.31?

**Comment by Rakshith-R** [comment]
> @Rakshith-R could we update the used k/k version to 1.30 or 1.31?

I am not sure, I don't think so.



> @Rakshith-R It looks strange to me. The log you posted shows
> 
> ```
> go: downloading go1.21.5 (linux/amd64)
> go: download go1.21.5 for linux/amd64: toolchain not available
> ```
> 
> But I got this locally.
> 
> ```
> GOTOOLCHAIN=go1.21.5 go version
> go: downloading go1.21.5 (darwin/arm64)
> go version go1.21.5 darwin/arm64
> ```
> 
> Can you check what the GOPROXY env is? The tool chain is downloaded there.

I added prow job logs here 
https://github.com/kubernetes-csi/csi-release-tools/pull/262#issuecomment-2531486038
I didn't find any GOPROXY env .

**Comment by huww98** [comment]
I think I've figured it out. v1.29 failed because It has `GOPROXY=off` in `kube::golang::build_some_binaries`. v1.30 is OK because it has the new `kube::golang::internal::verify_go_version` to trigger the download before the build.

**Comment by avorima** [comment]
@Rakshith-R yes, my bad i was thinking about the default version in prow.sh, but the test runs on 1.29 which can't be changed.

@huww98 i see the GOPROXY=off in the k/k repo. is that something that needs to be fixed there or do you think it can be fixed here?

**Comment by huww98** [comment]
@avorima I think #267 could fix this. It should ensure that Kubernetes also use the toolchain that we download, and does not need to download again.

**Comment by Rakshith-R** [comment]
Thanks for the quick fix !

**Pull request merged**
